In [ ]:
"""
Tutor MSAHIN
You can reach me on youtube, twitter, linkedin, medium and github with my @datasciengine username.
"""

## Don't Repeat Yourself! Use functions.

In [3]:
import cv2 as cv
import numpy as np

def show_img(img, img_name="Unknown"):
    cv.imshow(img_name, img)
    cv.waitKey(0)
    cv.destroyAllWindows()

In [4]:
who

cv	 np	 show_img	 


In [5]:
img = cv.imread('../VisualMaterials/Photos/people_2.jpg')
img

array([[[235, 229, 234],
        [235, 232, 234],
        [232, 236, 231],
        ...,
        [233, 207, 183],
        [233, 207, 183],
        [232, 206, 182]],

       [[230, 226, 231],
        [231, 230, 232],
        [233, 234, 232],
        ...,
        [233, 207, 183],
        [233, 207, 183],
        [233, 207, 183]],

       [[219, 222, 226],
        [226, 228, 229],
        [233, 231, 231],
        ...,
        [233, 207, 183],
        [233, 207, 183],
        [233, 207, 183]],

       ...,

       [[188, 185, 180],
        [188, 185, 180],
        [188, 185, 180],
        ...,
        [177, 182, 181],
        [176, 181, 180],
        [174, 179, 178]],

       [[189, 186, 181],
        [189, 186, 181],
        [189, 186, 181],
        ...,
        [177, 186, 189],
        [176, 185, 188],
        [174, 183, 186]],

       [[189, 186, 181],
        [189, 186, 181],
        [189, 186, 181],
        ...,
        [180, 191, 195],
        [179, 190, 194],
        [177, 188, 192]]

In [6]:
who

cv	 img	 np	 show_img	 


In [7]:
show_img(img=img, img_name="People")

Kontur, görüntü üzerindeki bir şeklin sınırları boyunca art arda devam eden noktalar bütününe verilen ad.

Konturları bulmadan önce bazı ön işleme aşamaları...

## GrayScale transformation

In [9]:
gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
show_img(gray, 'Gray')

## Blurring transformation

In [17]:
blur = cv.GaussianBlur(gray, (5,5), cv.BORDER_DEFAULT)
show_img(blur, 'Blur')

## Canny Algorithm

In [28]:
canny = cv.Canny(image=blur,
                 threshold1=125,
                 threshold2=175)

show_img(canny, 'canny')

In [23]:
ret, thresh_img = cv.threshold(gray, 125, 255, cv.THRESH_BINARY)

In [26]:
thresh_img

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [27]:
show_img(thresh_img, 'thresh_img')

In [29]:
contours, _ = cv.findContours(canny, cv.RETR_LIST, cv.CHAIN_APPROX_SIMPLE)
print(f'{len(contours)} contour(s) found!')

244 contour(s) found!


Peki bu elde ettiğimiz konturları

In [30]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
np.ones((2,5,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [32]:
np.full((5, 5, 3), 4)

array([[[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]],

       [[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]],

       [[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]],

       [[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]],

       [[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]]])

In [33]:
img.shape

(828, 640, 3)

In [34]:
blank = np.zeros(img.shape, dtype='uint8')
show_img(blank, img_name="Blank")

In [35]:
cv.drawContours(image=blank,
                contours=contours,
                contourIdx=-1,
                color=(0,0,255))

show_img(blank, 'Contours Drawn')